### ISSUE TITLE
cordova 6.4.0 - Installation issues 

### ISSUE THREAD

**Issue by iarjunphp** [paypal/PayPal-Cordova-Plugin#258]
$ cordova plugin add com.paypal.cordova.mobilesdk
Fetching plugin "com.paypal.cordova.mobilesdk" via npm

arjun@arjun-PC MINGW64 /d/New folder/MyShop
$ cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.mycompany.myshop
        Name: MyShop
        Activity: MainActivity
        Android target: android-24
Subproject Path: CordovaLib
Android project created with cordova-android@6.0.0
Installing "com.paypal.cordova.mobilesdk" for android
Fetching plugin "card.io.cordova.mobilesdk" via npm
Installing "card.io.cordova.mobilesdk" for android
ANDROID_HOME=C:\Users\arjun\AppData\Local\Android\android-sdk
JAVA_HOME=C:\Program Files\java\jdk1.8.0_60
Subproject Path: CordovaLib
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configur                                                                                                                ation failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:17                                                                                                                3)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.jav                                                                                                                a:645)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java                                                                                                                :156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java                                                                                                                :120)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.j                                                                                                                ava:603)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.d                                                                                                                ispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.d                                                                                                                ispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(Abstract                                                                                                                BroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc                                                                                                                h.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc                                                                                                                h.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocati                                                                                                                onHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfte                                                                                                                rEvaluate(LifecycleProjectEvaluator.java:67)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(L                                                                                                                ifecycleProjectEvaluator.java:61)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj                                                                                                                ect.java:540)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj                                                                                                                ect.java:93)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(Task                                                                                                                PathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuil                                                                                                                dConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLa                                                                                                                uncher.java:124)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                                                                tBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                                                                tBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default                                                                                                                GradleLauncher.java:121)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGra                                                                                                                dleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl                                                                                                                eLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl                                                                                                                eLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                                                                tBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                                                                tBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle                                                                                                                Launcher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun                                                                                                                cher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon                                                                                                                troller.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe                                                                                                                cuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA                                                                                                                ctionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce                                                                                                                ssBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce                                                                                                                ssBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin                                                                                                                uousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin                                                                                                                uousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBu                                                                                                                ild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build                                                                                                                CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(                                                                                                                DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(                                                                                                                WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(                                                                                                                DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute                                                                                                                (ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(                                                                                                                DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.                                                                                                                execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(                                                                                                                DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw                                                                                                                ardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw                                                                                                                ardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For                                                                                                                wardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(                                                                                                                DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(                                                                                                                DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(                                                                                                                DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien                                                                                                                t.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build                                                                                                                CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(                                                                                                                DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu                                                                                                                ild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build                                                                                                                CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(                                                                                                                DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(Hin                                                                                                                tGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(                                                                                                                DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.                                                                                                                run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(Daemon                                                                                                                StateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.                                                                                                                onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE                                                                                                                xecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                .java:617)
        at java.lang.Thread.run(Thread.java:745)

FAILURE: Build failed with an exception.

* Where:
Script 'D:\New folder\MyShop\platforms\android\CordovaLib\cordova.gradle' line:                                                                                                                 64

* What went wrong:
A problem occurred evaluating root project 'android'.
> No installed build tools found. Install the Android build tools version 19.1.0                                                                                                                 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                                                                 option to get more log output.

BUILD FAILED

Total time: 51.595 secs
Failed to install 'card.io.cordova.mobilesdk':Error: cmd: Command failed with ex                                                                                                                it code 1
    at ChildProcess.whenDone (D:\New folder\MyShop\platforms\android\cordova\nod                                                                                                                e_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Failed to install 'com.paypal.cordova.mobilesdk':Error: cmd: Command failed with                                                                                                                 exit code 1
    at ChildProcess.whenDone (D:\New folder\MyShop\platforms\android\cordova\nod                                                                                                                e_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: cmd: Command failed with exit code 1

**Comment by bluk** [comment]
Do you have the [Android Build Tools](https://developer.android.com/studio/releases/build-tools.html) installed on your system (usually installed with [Android Studio](https://developer.android.com/studio/index.html))? You should also check that any `build.gradle`-like file has a `buildToolsVersion` declaration. Something like:

```
    ext {
        compileSdkVersion = 24
        buildToolsVersion = '24.0.0'
        minSdkVersion = 15
        targetSdkVersion = 24
```

**Comment by pp-randy** [comment]
Closing the issue due to no further response being provided, please let us know if we need to assist further.
