### ISSUE TITLE
App Crashes Cordova 4.2 / Plugin 3.1.7

### ISSUE THREAD

**Issue by nwidal** [paypal/PayPal-Cordova-Plugin#79]
Hi,

my app got killed in Sandbox Mode, aftr fixing Netbeans IDE Bug which IU thoughed would cause the issue of killing my app when initialising the paypal plugin I got that log / stacktrace:

java.lang.IllegalStateException: Cannot get websocket address
	at org.netbeans.modules.cordova.platforms.android.AndroidDebugTransport.getURI(AndroidDebugTransport.java:226)
	at org.netbeans.modules.cordova.platforms.android.AndroidDebugTransport.createWebSocket(AndroidDebugTransport.java:129)
	at org.netbeans.modules.cordova.platforms.android.AndroidDebugTransport.attach(AndroidDebugTransport.java:146)
	at org.netbeans.modules.cordova.platforms.api.WebKitDebuggingSupport.startDebugging(WebKitDebuggingSupport.java:135)
	at org.netbeans.modules.cordova.CordovaPerformer$1.run(CordovaPerformer.java:250)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

Is there maybe a problem in configuration callback or clientID which could be null?

Code in angular called after onDeviceReady method:

app.factory('Wallet', function ($q, $window, $rootScope) {
    var service = {
        initPaymentUI: initPaymentUI,
        onSuccesfulPayment: onSuccesfulPayment,
        onFuturePaymentAuthorization: onFuturePaymentAuthorization,
        createPayment: createPayment,
        configuration: configuration,
        onPrepareRender: onPrepareRender,
        onPayPalMobileInit: onPayPalMobileInit,
        onUserCanceled: onUserCanceled,
        makePayment: makePayment
    };
    var clientIDs = {
        "PayPalEnvironmentProduction": "cvcxvdfrg...",
        "PayPalEnvironmentSandbox": "xccvb..."
    };

    function initPaymentUI() {
        var clientIDs = {
            "PayPalEnvironmentProduction": "xccvbvbn",
            "PayPalEnvironmentSandbox": "xccvbdfgfd-."
        };
        alert(clientIDs.PayPalEnvironmentSandbox);
        PayPalMobile.init(clientIDs, onPayPalMobileInit());

    }

    function onSuccesfulPayment(payment) {
        console.log("payment success: " + JSON.stringify(payment, null, 4));
        //alert("Zahlung erfolgreich");
    }

    function onFuturePaymentAuthorization(authorization) {
        console.log("authorization: " + JSON.stringify(authorization, null, 4));
    }
    function createPayment(summe, id, art) {
        // for simplicity use predefined amount
        var netto = summe / 1.19;
        var mwst = summe - netto;
        var paymentDetails = new PayPalPaymentDetails(netto, mwst);
        var payment = new PayPalPayment(summe, "EUR", id, art, paymentDetails);
        return payment;
    }
    function configuration() {
        // for more options see `paypal-mobile-js-helper.js`
        var config = new PayPalConfiguration({merchantName: "HKphotographics", merchantPrivacyPolicyURL: "https://www.bla.de", merchantUserAgreementURL: "https://www.bla.de/panel"});
        alert(config.toString());
        return config;
    }
    function onPayPalMobileInit() {
        // must be called
        // use PayPalEnvironmentNoNetwork mode to get look and feel of the flow
        //var config = configuration();
        PayPalMobile.prepareToRender("PayPalEnvironmentSandbox", configuration(), onPrepareRender());
    }
    function onUserCanceled(result) {
        console.log(result);
        //alert("Zahlung nicht erfolgreich.");
    }
    function onPrepareRender() {
        alert("onPrepareRend");
    }

    function makePayment(summe, id, art) {
        PayPalMobile.renderSinglePaymentUI(createPayment(summe, id, art), onSuccesfulPayment(), onUserCanceled());
    }

    return service;
});

**Comment by nwidal** [comment]
OK FIXED - Sorry for bothering. Only problem was that this implementation uses callbacks where just references should have been used. 
I think I'll update a proper angular wrapper and put it somewhere so ppl stop using this failure
